//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace MHSJ.Entity
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class MHSJEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“MHSJEntities”部分中的连接字符串初始化新 MHSJEntities 对象。
        /// </summary>
        public MHSJEntities() : base("name=MHSJEntities", "MHSJEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 MHSJEntities 对象。
        /// </summary>
        public MHSJEntities(string connectionString) : base(connectionString, "MHSJEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 MHSJEntities 对象。
        /// </summary>
        public MHSJEntities(EntityConnection connection) : base(connection, "MHSJEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<T_Writer> T_Writer
        {
            get
            {
                if ((_T_Writer == null))
                {
                    _T_Writer = base.CreateObjectSet<T_Writer>("T_Writer");
                }
                return _T_Writer;
            }
        }
        private ObjectSet<T_Writer> _T_Writer;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<T_From> T_From
        {
            get
            {
                if ((_T_From == null))
                {
                    _T_From = base.CreateObjectSet<T_From>("T_From");
                }
                return _T_From;
            }
        }
        private ObjectSet<T_From> _T_From;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<T_Sites> T_Sites
        {
            get
            {
                if ((_T_Sites == null))
                {
                    _T_Sites = base.CreateObjectSet<T_Sites>("T_Sites");
                }
                return _T_Sites;
            }
        }
        private ObjectSet<T_Sites> _T_Sites;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<T_Word> T_Word
        {
            get
            {
                if ((_T_Word == null))
                {
                    _T_Word = base.CreateObjectSet<T_Word>("T_Word");
                }
                return _T_Word;
            }
        }
        private ObjectSet<T_Word> _T_Word;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<T_Post> T_Post
        {
            get
            {
                if ((_T_Post == null))
                {
                    _T_Post = base.CreateObjectSet<T_Post>("T_Post");
                }
                return _T_Post;
            }
        }
        private ObjectSet<T_Post> _T_Post;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<V_Post> V_Post
        {
            get
            {
                if ((_V_Post == null))
                {
                    _V_Post = base.CreateObjectSet<V_Post>("V_Post");
                }
                return _V_Post;
            }
        }
        private ObjectSet<V_Post> _V_Post;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 T_Writer EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToT_Writer(T_Writer t_Writer)
        {
            base.AddObject("T_Writer", t_Writer);
        }
    
        /// <summary>
        /// 用于向 T_From EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToT_From(T_From t_From)
        {
            base.AddObject("T_From", t_From);
        }
    
        /// <summary>
        /// 用于向 T_Sites EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToT_Sites(T_Sites t_Sites)
        {
            base.AddObject("T_Sites", t_Sites);
        }
    
        /// <summary>
        /// 用于向 T_Word EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToT_Word(T_Word t_Word)
        {
            base.AddObject("T_Word", t_Word);
        }
    
        /// <summary>
        /// 用于向 T_Post EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToT_Post(T_Post t_Post)
        {
            base.AddObject("T_Post", t_Post);
        }
    
        /// <summary>
        /// 用于向 V_Post EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToV_Post(V_Post v_Post)
        {
            base.AddObject("V_Post", v_Post);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MHSJModel", Name="T_From")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_From : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 T_From 对象。
        /// </summary>
        /// <param name="fromId">FromId 属性的初始值。</param>
        /// <param name="displayOrder">DisplayOrder 属性的初始值。</param>
        public static T_From CreateT_From(global::System.Int32 fromId, global::System.Int32 displayOrder)
        {
            T_From t_From = new T_From();
            t_From.FromId = fromId;
            t_From.DisplayOrder = displayOrder;
            return t_From;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FromId
        {
            get
            {
                return _FromId;
            }
            set
            {
                if (_FromId != value)
                {
                    OnFromIdChanging(value);
                    ReportPropertyChanging("FromId");
                    _FromId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FromId");
                    OnFromIdChanged();
                }
            }
        }
        private global::System.Int32 _FromId;
        partial void OnFromIdChanging(global::System.Int32 value);
        partial void OnFromIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FromName
        {
            get
            {
                return _FromName;
            }
            set
            {
                OnFromNameChanging(value);
                ReportPropertyChanging("FromName");
                _FromName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FromName");
                OnFromNameChanged();
            }
        }
        private global::System.String _FromName;
        partial void OnFromNameChanging(global::System.String value);
        partial void OnFromNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FromAliases
        {
            get
            {
                return _FromAliases;
            }
            set
            {
                OnFromAliasesChanging(value);
                ReportPropertyChanging("FromAliases");
                _FromAliases = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FromAliases");
                OnFromAliasesChanged();
            }
        }
        private global::System.String _FromAliases;
        partial void OnFromAliasesChanging(global::System.String value);
        partial void OnFromAliasesChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DisplayOrder
        {
            get
            {
                return _DisplayOrder;
            }
            set
            {
                OnDisplayOrderChanging(value);
                ReportPropertyChanging("DisplayOrder");
                _DisplayOrder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DisplayOrder");
                OnDisplayOrderChanged();
            }
        }
        private global::System.Int32 _DisplayOrder;
        partial void OnDisplayOrderChanging(global::System.Int32 value);
        partial void OnDisplayOrderChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateDate;
        partial void OnCreateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UpdateDate
        {
            get
            {
                return _UpdateDate;
            }
            set
            {
                OnUpdateDateChanging(value);
                ReportPropertyChanging("UpdateDate");
                _UpdateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdateDate");
                OnUpdateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _UpdateDate;
        partial void OnUpdateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnUpdateDateChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MHSJModel", Name="T_Post")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_Post : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 T_Post 对象。
        /// </summary>
        /// <param name="postId">PostId 属性的初始值。</param>
        public static T_Post CreateT_Post(global::System.Int32 postId)
        {
            T_Post t_Post = new T_Post();
            t_Post.PostId = postId;
            return t_Post;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PostId
        {
            get
            {
                return _PostId;
            }
            set
            {
                if (_PostId != value)
                {
                    OnPostIdChanging(value);
                    ReportPropertyChanging("PostId");
                    _PostId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PostId");
                    OnPostIdChanged();
                }
            }
        }
        private global::System.Int32 _PostId;
        partial void OnPostIdChanging(global::System.Int32 value);
        partial void OnPostIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SimplifiedWord
        {
            get
            {
                return _SimplifiedWord;
            }
            set
            {
                OnSimplifiedWordChanging(value);
                ReportPropertyChanging("SimplifiedWord");
                _SimplifiedWord = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SimplifiedWord");
                OnSimplifiedWordChanged();
            }
        }
        private global::System.String _SimplifiedWord;
        partial void OnSimplifiedWordChanging(global::System.String value);
        partial void OnSimplifiedWordChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TraditionalWord
        {
            get
            {
                return _TraditionalWord;
            }
            set
            {
                OnTraditionalWordChanging(value);
                ReportPropertyChanging("TraditionalWord");
                _TraditionalWord = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TraditionalWord");
                OnTraditionalWordChanged();
            }
        }
        private global::System.String _TraditionalWord;
        partial void OnTraditionalWordChanging(global::System.String value);
        partial void OnTraditionalWordChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Pinyin
        {
            get
            {
                return _Pinyin;
            }
            set
            {
                OnPinyinChanging(value);
                ReportPropertyChanging("Pinyin");
                _Pinyin = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Pinyin");
                OnPinyinChanged();
            }
        }
        private global::System.String _Pinyin;
        partial void OnPinyinChanging(global::System.String value);
        partial void OnPinyinChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Wubi
        {
            get
            {
                return _Wubi;
            }
            set
            {
                OnWubiChanging(value);
                ReportPropertyChanging("Wubi");
                _Wubi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Wubi");
                OnWubiChanged();
            }
        }
        private global::System.String _Wubi;
        partial void OnWubiChanging(global::System.String value);
        partial void OnWubiChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Changjei
        {
            get
            {
                return _Changjei;
            }
            set
            {
                OnChangjeiChanging(value);
                ReportPropertyChanging("Changjei");
                _Changjei = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Changjei");
                OnChangjeiChanged();
            }
        }
        private global::System.String _Changjei;
        partial void OnChangjeiChanging(global::System.String value);
        partial void OnChangjeiChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Zhengma
        {
            get
            {
                return _Zhengma;
            }
            set
            {
                OnZhengmaChanging(value);
                ReportPropertyChanging("Zhengma");
                _Zhengma = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Zhengma");
                OnZhengmaChanged();
            }
        }
        private global::System.String _Zhengma;
        partial void OnZhengmaChanging(global::System.String value);
        partial void OnZhengmaChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Bushou
        {
            get
            {
                return _Bushou;
            }
            set
            {
                OnBushouChanging(value);
                ReportPropertyChanging("Bushou");
                _Bushou = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Bushou");
                OnBushouChanged();
            }
        }
        private global::System.String _Bushou;
        partial void OnBushouChanging(global::System.String value);
        partial void OnBushouChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tongjia
        {
            get
            {
                return _Tongjia;
            }
            set
            {
                OnTongjiaChanging(value);
                ReportPropertyChanging("Tongjia");
                _Tongjia = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tongjia");
                OnTongjiaChanged();
            }
        }
        private global::System.String _Tongjia;
        partial void OnTongjiaChanging(global::System.String value);
        partial void OnTongjiaChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Yiti
        {
            get
            {
                return _Yiti;
            }
            set
            {
                OnYitiChanging(value);
                ReportPropertyChanging("Yiti");
                _Yiti = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Yiti");
                OnYitiChanged();
            }
        }
        private global::System.String _Yiti;
        partial void OnYitiChanging(global::System.String value);
        partial void OnYitiChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WordType
        {
            get
            {
                return _WordType;
            }
            set
            {
                OnWordTypeChanging(value);
                ReportPropertyChanging("WordType");
                _WordType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("WordType");
                OnWordTypeChanged();
            }
        }
        private global::System.String _WordType;
        partial void OnWordTypeChanging(global::System.String value);
        partial void OnWordTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WordTypeName
        {
            get
            {
                return _WordTypeName;
            }
            set
            {
                OnWordTypeNameChanging(value);
                ReportPropertyChanging("WordTypeName");
                _WordTypeName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("WordTypeName");
                OnWordTypeNameChanged();
            }
        }
        private global::System.String _WordTypeName;
        partial void OnWordTypeNameChanging(global::System.String value);
        partial void OnWordTypeNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WordDirection
        {
            get
            {
                return _WordDirection;
            }
            set
            {
                OnWordDirectionChanging(value);
                ReportPropertyChanging("WordDirection");
                _WordDirection = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("WordDirection");
                OnWordDirectionChanged();
            }
        }
        private global::System.String _WordDirection;
        partial void OnWordDirectionChanging(global::System.String value);
        partial void OnWordDirectionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> WriterId
        {
            get
            {
                return _WriterId;
            }
            set
            {
                OnWriterIdChanging(value);
                ReportPropertyChanging("WriterId");
                _WriterId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WriterId");
                OnWriterIdChanged();
            }
        }
        private Nullable<global::System.Int32> _WriterId;
        partial void OnWriterIdChanging(Nullable<global::System.Int32> value);
        partial void OnWriterIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WriterName
        {
            get
            {
                return _WriterName;
            }
            set
            {
                OnWriterNameChanging(value);
                ReportPropertyChanging("WriterName");
                _WriterName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("WriterName");
                OnWriterNameChanged();
            }
        }
        private global::System.String _WriterName;
        partial void OnWriterNameChanging(global::System.String value);
        partial void OnWriterNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FromId
        {
            get
            {
                return _FromId;
            }
            set
            {
                OnFromIdChanging(value);
                ReportPropertyChanging("FromId");
                _FromId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FromId");
                OnFromIdChanged();
            }
        }
        private Nullable<global::System.Int32> _FromId;
        partial void OnFromIdChanging(Nullable<global::System.Int32> value);
        partial void OnFromIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FromName
        {
            get
            {
                return _FromName;
            }
            set
            {
                OnFromNameChanging(value);
                ReportPropertyChanging("FromName");
                _FromName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FromName");
                OnFromNameChanged();
            }
        }
        private global::System.String _FromName;
        partial void OnFromNameChanging(global::System.String value);
        partial void OnFromNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImageUrl
        {
            get
            {
                return _ImageUrl;
            }
            set
            {
                OnImageUrlChanging(value);
                ReportPropertyChanging("ImageUrl");
                _ImageUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImageUrl");
                OnImageUrlChanged();
            }
        }
        private global::System.String _ImageUrl;
        partial void OnImageUrlChanging(global::System.String value);
        partial void OnImageUrlChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> WordId
        {
            get
            {
                return _WordId;
            }
            set
            {
                OnWordIdChanging(value);
                ReportPropertyChanging("WordId");
                _WordId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WordId");
                OnWordIdChanged();
            }
        }
        private Nullable<global::System.Int32> _WordId;
        partial void OnWordIdChanging(Nullable<global::System.Int32> value);
        partial void OnWordIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Word
        {
            get
            {
                return _Word;
            }
            set
            {
                OnWordChanging(value);
                ReportPropertyChanging("Word");
                _Word = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Word");
                OnWordChanged();
            }
        }
        private global::System.String _Word;
        partial void OnWordChanging(global::System.String value);
        partial void OnWordChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TWord
        {
            get
            {
                return _TWord;
            }
            set
            {
                OnTWordChanging(value);
                ReportPropertyChanging("TWord");
                _TWord = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TWord");
                OnTWordChanged();
            }
        }
        private global::System.String _TWord;
        partial void OnTWordChanging(global::System.String value);
        partial void OnTWordChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private Nullable<global::System.Int32> _State;
        partial void OnStateChanging(Nullable<global::System.Int32> value);
        partial void OnStateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateDate;
        partial void OnCreateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UpdateDate
        {
            get
            {
                return _UpdateDate;
            }
            set
            {
                OnUpdateDateChanging(value);
                ReportPropertyChanging("UpdateDate");
                _UpdateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdateDate");
                OnUpdateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _UpdateDate;
        partial void OnUpdateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnUpdateDateChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MHSJModel", Name="T_Sites")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_Sites : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 T_Sites 对象。
        /// </summary>
        /// <param name="siteId">SiteId 属性的初始值。</param>
        public static T_Sites CreateT_Sites(global::System.Int32 siteId)
        {
            T_Sites t_Sites = new T_Sites();
            t_Sites.SiteId = siteId;
            return t_Sites;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SiteId
        {
            get
            {
                return _SiteId;
            }
            set
            {
                if (_SiteId != value)
                {
                    OnSiteIdChanging(value);
                    ReportPropertyChanging("SiteId");
                    _SiteId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SiteId");
                    OnSiteIdChanged();
                }
            }
        }
        private global::System.Int32 _SiteId;
        partial void OnSiteIdChanging(global::System.Int32 value);
        partial void OnSiteIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PostCount
        {
            get
            {
                return _PostCount;
            }
            set
            {
                OnPostCountChanging(value);
                ReportPropertyChanging("PostCount");
                _PostCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PostCount");
                OnPostCountChanged();
            }
        }
        private Nullable<global::System.Int32> _PostCount;
        partial void OnPostCountChanging(Nullable<global::System.Int32> value);
        partial void OnPostCountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CommentCount
        {
            get
            {
                return _CommentCount;
            }
            set
            {
                OnCommentCountChanging(value);
                ReportPropertyChanging("CommentCount");
                _CommentCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CommentCount");
                OnCommentCountChanged();
            }
        }
        private Nullable<global::System.Int32> _CommentCount;
        partial void OnCommentCountChanging(Nullable<global::System.Int32> value);
        partial void OnCommentCountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> VisitCount
        {
            get
            {
                return _VisitCount;
            }
            set
            {
                OnVisitCountChanging(value);
                ReportPropertyChanging("VisitCount");
                _VisitCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VisitCount");
                OnVisitCountChanged();
            }
        }
        private Nullable<global::System.Int32> _VisitCount;
        partial void OnVisitCountChanging(Nullable<global::System.Int32> value);
        partial void OnVisitCountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TagCount
        {
            get
            {
                return _TagCount;
            }
            set
            {
                OnTagCountChanging(value);
                ReportPropertyChanging("TagCount");
                _TagCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TagCount");
                OnTagCountChanged();
            }
        }
        private Nullable<global::System.Int32> _TagCount;
        partial void OnTagCountChanging(Nullable<global::System.Int32> value);
        partial void OnTagCountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Setting
        {
            get
            {
                return _Setting;
            }
            set
            {
                OnSettingChanging(value);
                ReportPropertyChanging("Setting");
                _Setting = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Setting");
                OnSettingChanged();
            }
        }
        private global::System.String _Setting;
        partial void OnSettingChanging(global::System.String value);
        partial void OnSettingChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MHSJModel", Name="T_Word")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_Word : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 T_Word 对象。
        /// </summary>
        /// <param name="wordId">WordId 属性的初始值。</param>
        public static T_Word CreateT_Word(global::System.Int32 wordId)
        {
            T_Word t_Word = new T_Word();
            t_Word.WordId = wordId;
            return t_Word;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 WordId
        {
            get
            {
                return _WordId;
            }
            set
            {
                if (_WordId != value)
                {
                    OnWordIdChanging(value);
                    ReportPropertyChanging("WordId");
                    _WordId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("WordId");
                    OnWordIdChanged();
                }
            }
        }
        private global::System.Int32 _WordId;
        partial void OnWordIdChanging(global::System.Int32 value);
        partial void OnWordIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SimplifiedWord
        {
            get
            {
                return _SimplifiedWord;
            }
            set
            {
                OnSimplifiedWordChanging(value);
                ReportPropertyChanging("SimplifiedWord");
                _SimplifiedWord = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SimplifiedWord");
                OnSimplifiedWordChanged();
            }
        }
        private global::System.String _SimplifiedWord;
        partial void OnSimplifiedWordChanging(global::System.String value);
        partial void OnSimplifiedWordChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TraditionalWord
        {
            get
            {
                return _TraditionalWord;
            }
            set
            {
                OnTraditionalWordChanging(value);
                ReportPropertyChanging("TraditionalWord");
                _TraditionalWord = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TraditionalWord");
                OnTraditionalWordChanged();
            }
        }
        private global::System.String _TraditionalWord;
        partial void OnTraditionalWordChanging(global::System.String value);
        partial void OnTraditionalWordChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Pinyin
        {
            get
            {
                return _Pinyin;
            }
            set
            {
                OnPinyinChanging(value);
                ReportPropertyChanging("Pinyin");
                _Pinyin = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Pinyin");
                OnPinyinChanged();
            }
        }
        private global::System.String _Pinyin;
        partial void OnPinyinChanging(global::System.String value);
        partial void OnPinyinChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Wubi
        {
            get
            {
                return _Wubi;
            }
            set
            {
                OnWubiChanging(value);
                ReportPropertyChanging("Wubi");
                _Wubi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Wubi");
                OnWubiChanged();
            }
        }
        private global::System.String _Wubi;
        partial void OnWubiChanging(global::System.String value);
        partial void OnWubiChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Changjei
        {
            get
            {
                return _Changjei;
            }
            set
            {
                OnChangjeiChanging(value);
                ReportPropertyChanging("Changjei");
                _Changjei = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Changjei");
                OnChangjeiChanged();
            }
        }
        private global::System.String _Changjei;
        partial void OnChangjeiChanging(global::System.String value);
        partial void OnChangjeiChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Zhengma
        {
            get
            {
                return _Zhengma;
            }
            set
            {
                OnZhengmaChanging(value);
                ReportPropertyChanging("Zhengma");
                _Zhengma = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Zhengma");
                OnZhengmaChanged();
            }
        }
        private global::System.String _Zhengma;
        partial void OnZhengmaChanging(global::System.String value);
        partial void OnZhengmaChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Bushou
        {
            get
            {
                return _Bushou;
            }
            set
            {
                OnBushouChanging(value);
                ReportPropertyChanging("Bushou");
                _Bushou = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Bushou");
                OnBushouChanged();
            }
        }
        private global::System.String _Bushou;
        partial void OnBushouChanging(global::System.String value);
        partial void OnBushouChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tongjia
        {
            get
            {
                return _Tongjia;
            }
            set
            {
                OnTongjiaChanging(value);
                ReportPropertyChanging("Tongjia");
                _Tongjia = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tongjia");
                OnTongjiaChanged();
            }
        }
        private global::System.String _Tongjia;
        partial void OnTongjiaChanging(global::System.String value);
        partial void OnTongjiaChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Yiti
        {
            get
            {
                return _Yiti;
            }
            set
            {
                OnYitiChanging(value);
                ReportPropertyChanging("Yiti");
                _Yiti = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Yiti");
                OnYitiChanged();
            }
        }
        private global::System.String _Yiti;
        partial void OnYitiChanging(global::System.String value);
        partial void OnYitiChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private Nullable<global::System.Int32> _State;
        partial void OnStateChanging(Nullable<global::System.Int32> value);
        partial void OnStateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateDate;
        partial void OnCreateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UpdateDate
        {
            get
            {
                return _UpdateDate;
            }
            set
            {
                OnUpdateDateChanging(value);
                ReportPropertyChanging("UpdateDate");
                _UpdateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdateDate");
                OnUpdateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _UpdateDate;
        partial void OnUpdateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnUpdateDateChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MHSJModel", Name="T_Writer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_Writer : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 T_Writer 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        /// <param name="writerName">WriterName 属性的初始值。</param>
        /// <param name="displayOrder">DisplayOrder 属性的初始值。</param>
        public static T_Writer CreateT_Writer(global::System.Int32 id, global::System.String writerName, global::System.Int32 displayOrder)
        {
            T_Writer t_Writer = new T_Writer();
            t_Writer.Id = id;
            t_Writer.WriterName = writerName;
            t_Writer.DisplayOrder = displayOrder;
            return t_Writer;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String WriterName
        {
            get
            {
                return _WriterName;
            }
            set
            {
                OnWriterNameChanging(value);
                ReportPropertyChanging("WriterName");
                _WriterName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("WriterName");
                OnWriterNameChanged();
            }
        }
        private global::System.String _WriterName;
        partial void OnWriterNameChanging(global::System.String value);
        partial void OnWriterNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WriterAliases
        {
            get
            {
                return _WriterAliases;
            }
            set
            {
                OnWriterAliasesChanging(value);
                ReportPropertyChanging("WriterAliases");
                _WriterAliases = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("WriterAliases");
                OnWriterAliasesChanged();
            }
        }
        private global::System.String _WriterAliases;
        partial void OnWriterAliasesChanging(global::System.String value);
        partial void OnWriterAliasesChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Dynasty
        {
            get
            {
                return _Dynasty;
            }
            set
            {
                OnDynastyChanging(value);
                ReportPropertyChanging("Dynasty");
                _Dynasty = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Dynasty");
                OnDynastyChanged();
            }
        }
        private global::System.String _Dynasty;
        partial void OnDynastyChanging(global::System.String value);
        partial void OnDynastyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DisplayOrder
        {
            get
            {
                return _DisplayOrder;
            }
            set
            {
                OnDisplayOrderChanging(value);
                ReportPropertyChanging("DisplayOrder");
                _DisplayOrder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DisplayOrder");
                OnDisplayOrderChanged();
            }
        }
        private global::System.Int32 _DisplayOrder;
        partial void OnDisplayOrderChanging(global::System.Int32 value);
        partial void OnDisplayOrderChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private Nullable<global::System.Int32> _Status;
        partial void OnStatusChanging(Nullable<global::System.Int32> value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateDate;
        partial void OnCreateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UpdateDate
        {
            get
            {
                return _UpdateDate;
            }
            set
            {
                OnUpdateDateChanging(value);
                ReportPropertyChanging("UpdateDate");
                _UpdateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdateDate");
                OnUpdateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _UpdateDate;
        partial void OnUpdateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnUpdateDateChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MHSJModel", Name="V_Post")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class V_Post : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 V_Post 对象。
        /// </summary>
        /// <param name="postId">PostId 属性的初始值。</param>
        public static V_Post CreateV_Post(global::System.Int32 postId)
        {
            V_Post v_Post = new V_Post();
            v_Post.PostId = postId;
            return v_Post;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PostId
        {
            get
            {
                return _PostId;
            }
            set
            {
                if (_PostId != value)
                {
                    OnPostIdChanging(value);
                    ReportPropertyChanging("PostId");
                    _PostId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PostId");
                    OnPostIdChanged();
                }
            }
        }
        private global::System.Int32 _PostId;
        partial void OnPostIdChanging(global::System.Int32 value);
        partial void OnPostIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> WordId
        {
            get
            {
                return _WordId;
            }
            set
            {
                OnWordIdChanging(value);
                ReportPropertyChanging("WordId");
                _WordId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WordId");
                OnWordIdChanged();
            }
        }
        private Nullable<global::System.Int32> _WordId;
        partial void OnWordIdChanging(Nullable<global::System.Int32> value);
        partial void OnWordIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SimplifiedWord
        {
            get
            {
                return _SimplifiedWord;
            }
            set
            {
                OnSimplifiedWordChanging(value);
                ReportPropertyChanging("SimplifiedWord");
                _SimplifiedWord = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SimplifiedWord");
                OnSimplifiedWordChanged();
            }
        }
        private global::System.String _SimplifiedWord;
        partial void OnSimplifiedWordChanging(global::System.String value);
        partial void OnSimplifiedWordChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TraditionalWord
        {
            get
            {
                return _TraditionalWord;
            }
            set
            {
                OnTraditionalWordChanging(value);
                ReportPropertyChanging("TraditionalWord");
                _TraditionalWord = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TraditionalWord");
                OnTraditionalWordChanged();
            }
        }
        private global::System.String _TraditionalWord;
        partial void OnTraditionalWordChanging(global::System.String value);
        partial void OnTraditionalWordChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Pinyin
        {
            get
            {
                return _Pinyin;
            }
            set
            {
                OnPinyinChanging(value);
                ReportPropertyChanging("Pinyin");
                _Pinyin = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Pinyin");
                OnPinyinChanged();
            }
        }
        private global::System.String _Pinyin;
        partial void OnPinyinChanging(global::System.String value);
        partial void OnPinyinChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Wubi
        {
            get
            {
                return _Wubi;
            }
            set
            {
                OnWubiChanging(value);
                ReportPropertyChanging("Wubi");
                _Wubi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Wubi");
                OnWubiChanged();
            }
        }
        private global::System.String _Wubi;
        partial void OnWubiChanging(global::System.String value);
        partial void OnWubiChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Changjei
        {
            get
            {
                return _Changjei;
            }
            set
            {
                OnChangjeiChanging(value);
                ReportPropertyChanging("Changjei");
                _Changjei = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Changjei");
                OnChangjeiChanged();
            }
        }
        private global::System.String _Changjei;
        partial void OnChangjeiChanging(global::System.String value);
        partial void OnChangjeiChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Zhengma
        {
            get
            {
                return _Zhengma;
            }
            set
            {
                OnZhengmaChanging(value);
                ReportPropertyChanging("Zhengma");
                _Zhengma = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Zhengma");
                OnZhengmaChanged();
            }
        }
        private global::System.String _Zhengma;
        partial void OnZhengmaChanging(global::System.String value);
        partial void OnZhengmaChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String bsWord
        {
            get
            {
                return _bsWord;
            }
            set
            {
                OnbsWordChanging(value);
                ReportPropertyChanging("bsWord");
                _bsWord = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("bsWord");
                OnbsWordChanged();
            }
        }
        private global::System.String _bsWord;
        partial void OnbsWordChanging(global::System.String value);
        partial void OnbsWordChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tongjia
        {
            get
            {
                return _Tongjia;
            }
            set
            {
                OnTongjiaChanging(value);
                ReportPropertyChanging("Tongjia");
                _Tongjia = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tongjia");
                OnTongjiaChanged();
            }
        }
        private global::System.String _Tongjia;
        partial void OnTongjiaChanging(global::System.String value);
        partial void OnTongjiaChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Yiti
        {
            get
            {
                return _Yiti;
            }
            set
            {
                OnYitiChanging(value);
                ReportPropertyChanging("Yiti");
                _Yiti = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Yiti");
                OnYitiChanged();
            }
        }
        private global::System.String _Yiti;
        partial void OnYitiChanging(global::System.String value);
        partial void OnYitiChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tword
        {
            get
            {
                return _Tword;
            }
            set
            {
                OnTwordChanging(value);
                ReportPropertyChanging("Tword");
                _Tword = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tword");
                OnTwordChanged();
            }
        }
        private global::System.String _Tword;
        partial void OnTwordChanging(global::System.String value);
        partial void OnTwordChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Bushou
        {
            get
            {
                return _Bushou;
            }
            set
            {
                OnBushouChanging(value);
                ReportPropertyChanging("Bushou");
                _Bushou = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Bushou");
                OnBushouChanged();
            }
        }
        private global::System.String _Bushou;
        partial void OnBushouChanging(global::System.String value);
        partial void OnBushouChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WordType
        {
            get
            {
                return _WordType;
            }
            set
            {
                OnWordTypeChanging(value);
                ReportPropertyChanging("WordType");
                _WordType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("WordType");
                OnWordTypeChanged();
            }
        }
        private global::System.String _WordType;
        partial void OnWordTypeChanging(global::System.String value);
        partial void OnWordTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WordTypeName
        {
            get
            {
                return _WordTypeName;
            }
            set
            {
                OnWordTypeNameChanging(value);
                ReportPropertyChanging("WordTypeName");
                _WordTypeName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("WordTypeName");
                OnWordTypeNameChanged();
            }
        }
        private global::System.String _WordTypeName;
        partial void OnWordTypeNameChanging(global::System.String value);
        partial void OnWordTypeNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WordDirection
        {
            get
            {
                return _WordDirection;
            }
            set
            {
                OnWordDirectionChanging(value);
                ReportPropertyChanging("WordDirection");
                _WordDirection = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("WordDirection");
                OnWordDirectionChanged();
            }
        }
        private global::System.String _WordDirection;
        partial void OnWordDirectionChanging(global::System.String value);
        partial void OnWordDirectionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> WriterId
        {
            get
            {
                return _WriterId;
            }
            set
            {
                OnWriterIdChanging(value);
                ReportPropertyChanging("WriterId");
                _WriterId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WriterId");
                OnWriterIdChanged();
            }
        }
        private Nullable<global::System.Int32> _WriterId;
        partial void OnWriterIdChanging(Nullable<global::System.Int32> value);
        partial void OnWriterIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WriterName
        {
            get
            {
                return _WriterName;
            }
            set
            {
                OnWriterNameChanging(value);
                ReportPropertyChanging("WriterName");
                _WriterName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("WriterName");
                OnWriterNameChanged();
            }
        }
        private global::System.String _WriterName;
        partial void OnWriterNameChanging(global::System.String value);
        partial void OnWriterNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FromId
        {
            get
            {
                return _FromId;
            }
            set
            {
                OnFromIdChanging(value);
                ReportPropertyChanging("FromId");
                _FromId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FromId");
                OnFromIdChanged();
            }
        }
        private Nullable<global::System.Int32> _FromId;
        partial void OnFromIdChanging(Nullable<global::System.Int32> value);
        partial void OnFromIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FromName
        {
            get
            {
                return _FromName;
            }
            set
            {
                OnFromNameChanging(value);
                ReportPropertyChanging("FromName");
                _FromName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FromName");
                OnFromNameChanged();
            }
        }
        private global::System.String _FromName;
        partial void OnFromNameChanging(global::System.String value);
        partial void OnFromNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImageUrl
        {
            get
            {
                return _ImageUrl;
            }
            set
            {
                OnImageUrlChanging(value);
                ReportPropertyChanging("ImageUrl");
                _ImageUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImageUrl");
                OnImageUrlChanged();
            }
        }
        private global::System.String _ImageUrl;
        partial void OnImageUrlChanging(global::System.String value);
        partial void OnImageUrlChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateDate;
        partial void OnCreateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UpdateDate
        {
            get
            {
                return _UpdateDate;
            }
            set
            {
                OnUpdateDateChanging(value);
                ReportPropertyChanging("UpdateDate");
                _UpdateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdateDate");
                OnUpdateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _UpdateDate;
        partial void OnUpdateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnUpdateDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private Nullable<global::System.Int32> _State;
        partial void OnStateChanging(Nullable<global::System.Int32> value);
        partial void OnStateChanged();

        #endregion

    
    }

    #endregion

    
}
